---
# tasks file for apache_config
- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install Apache package
  become: true
  apt:
    name: apache2
    state: present

- name: Ensure Apache service is running and enabled
  become: true
  service:
    name: apache2
    state: restarted
    enabled: yes
