---
# tasks file for apache_config
- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install Apache package
  become: true
  apt:
    name: apache2
    state: present

- name: Copy bootstrap.ign
  become: true
  template:
    src: "{{ role_path }}/files/bootstrap.ign"
    dest: /var/www/html/okd/
    owner: root
    mode: 0644

- name: Copy master.ign
  become: true
  template:
    src: "{{ role_path }}/files/master.ign"
    dest: /var/www/html/okd/
    owner: root
    mode: 0644

- name: Copy worker.ign
  become: true
  template:
    src: "{{ role_path }}/files/worker.ign"
    dest: /var/www/html/okd/
    owner: root
    mode: 0644

- name: Ensure Apache service is running and enabled
  become: true
  service:
    name: apache2
    state: restarted
    enabled: yes
