---
# tasks file for haproxy_config
- name: Set masters variable
  set_fact:
    masters: "{{ openshift.cluster.masters }}"

- name: Set workers variable
  set_fact:
    workers: "{{ openshift.cluster.workers }}"

- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install haproxy package
  become: true
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration template
  become: true
  template:
    src: "{{ role_path }}/files/haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: Ensure haproxy service is running and enabled
  service:
    name: haproxy
    state: started
    enabled: yes
