- name: Set dns_servers variable
  set_fact:
    dns_servers: "{{ openshift.dns.servers }}"

- name: Create Netplan configuration with custom DNS
  become: true
  template:
    src: "{{ role_path }}/templates/netplan.yaml.j2"
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0600

- name: Apply Netplan configuration
  become: true
  command: netplan apply
